### ISSUE TITLE
Segfault on '.importobj "nonexistent.o"'

### ISSUE THREAD

**Issue by Sagiri** [Kingcom/armips#141]
Looks to be caused by loadArArchive (in Core/Elf/ElfRelocator.cpp) not noticing the ByteArray wasn't initialized properly.

**Comment by sp1187** [comment]
Should be fixed by 725a6bb7508e18e4fd3340ebafb6cbf05048a30d, though I guess it would be a good idea to introduce more detailed error messages in the future.
