### ISSUE TITLE
Command line arguments -equ and -strequ case weirdness

### ISSUE THREAD

**Issue by Sagiri** [Kingcom/armips#142]
For example, if `test.asm` contains just:

```
.warning STRING
```

And you invoke it with `armips test.asm -strequ STRING something`, you get an error complaining that the label `string` does not exist. It works if you invoke it with `armips test.asm -strequ string something` instead.

It seems like the command line argument parser needs to lowercase the names (like is done in other contexts, such as a literal `EQU` in source) to make it properly case-insensitive, as it is elsewhere.

This applies to both `-equ` and `-strequ`, as the title implies.

**Comment by sp1187** [comment]
Fixed by 8632b9ffd26336b588d368fcbca1c6457510af87.
