### ISSUE TITLE
No rfe (cop0 0x10) instruction (PSX MIPS)

### ISSUE THREAD

**Issue by Lameguy64** [Kingcom/armips#154]
This instruction is simply a macro of cop0 0x10 which is used to return from an exception state on the PSX and is necessary for writing debug monitors and custom cheat cartridge firmware that utilize a cop0 breakpoint based execution hook. The GNU assembler (from GCC) supports this opcode when configured for mipsel.

My current workaround is to use a .word directive with the opcode for rfe/cop0 0x10:
`.macro rfe
	.word 0x42000010
.endmacro`

**Comment by sp1187** [comment]
Fixed by https://github.com/Kingcom/armips/commit/d31ec6bf3eed7ce2012f884bd6cf93790d68b8e9. Also enabled the COP0 TLB instructions, which were incorrectly disabled for PSX.
