### ISSUE TITLE
Parameter failure when adding label to 0x constant ending in E

### ISSUE THREAD

**Issue by Prof9** [Kingcom/armips#156]
```
.gba
.open "input.gba","output.gba",0x8000000

test:
	.dw	0xE+test

.close
```
This very simple input .asm file throws the following error on 7aa5cba:
```
src.asm(5) error: Parameter failure
Aborting.
```

For some reason this ONLY happens when the constant ends with an E. For example: `0xD` works, `0xF` works. `0x1E` fails, `0x2E` fails, and so on. I've tried various label names and file addresses, but these don't seem to affect it.

Wrapping the `0xE` in parentheses, e.g. `.dw (0xE)+test` _does_ make it work.  But this should not be needed for such a simple addition. Furthermore, formatting the constant differently--such as `0Eh` or `14`--also makes it work.

What also works is adding spaces around the `+`. However, if you only add a space to the right, e.g. `.dw 0xE+ test`, then you get a different error (and again this only happens when the constant ends in E):
```
src.asm(5) error: Directive not terminated
Aborting.
```
```

**Comment by sp1187** [comment]
Should be fixed by https://github.com/Kingcom/armips/commit/0292c939f3895779aadec1dd59b67403a2a30fa6.

**Comment by Prof9** [comment]
Darn! I was just about to submit the PR. Thanks for the quick fix. I'll just submit my test case instead.

**Comment by sp1187** [comment]
If you can find a edge case that I somehow missed, that would be welcome too.
