### ISSUE TITLE
Peculiar error when file is closed in the middle of an area

### ISSUE THREAD

**Issue by Prof9** [Kingcom/armips#180]
Given the following .asm file:
```
.gba
.create "out.bin",0

.area 0x4
.fill 0x8
.close
.endarea
```
This yields the following error message:
```
test.asm(4) error: No file opened
```
Line 4 is the one with `.area 0x4`. However, at the point the area is declared, the file is still open, so this error seems strange to me. The same happens when using `.region` and `.endregion` instead.

I suggest to instead throw a more specific error when `.close` is used in the middle of an area or region.

**Comment by unknownbrackets** [comment]
Is there a reason to be able to `.open`, `.create`, or `.close` within any of the following directives?

 * `.region`, `.autoregion`, `.area`
 * `.func` / `.function`

Seems to me it should error if you try to change the file within any of those.

-[Unknown]

**Comment by Prof9** [comment]
No, I agree, but the current error thrown by armips doesn't go a good job pointing out the issue. In this example the `.area` and `.close` are close to each other, but that needn't always be the case.
