### ISSUE TITLE
"Mismatched R_MIPS_HI16 with R_MIPS_LO16 of a different symbol" with PSX .obj files

### ISSUE THREAD

**Issue by RSolidSnake11** [Kingcom/armips#187]
In the latest build of armips (2020-08-11 14:18:03), if you try to import any .obj file compiled with CCPSX, you get the following error: ``` Mismatched R_MIPS_HI16 with R_MIPS_LO16 of a different symbol```, in my case, the error is present at line 45, where I use ".importobj" to import the object file.
```asm
.org 0x80029094
	jal debug ; I call the function contained in the OBJ here
.org 0x800111C0
	.area 0x200, 0x00
	  .importobj "debug.obj" ;This is where the error gets triggered
	.endarea
.close
```
The C object file that I've compiled is the following: 
```C
#include "debug.h"
void debug ()
{
	looping_func();
	print_main(0x32, 0x44, 0x8000, "%d  %d  %d  %d", playerX, playerY, playerZ, health);
}
```
...while the options that I've used for the C object file are: ```ccpsx -O2  -Wall -c debug.c ```.
The project used to compile with no issues on earlier builds, so I'm not sure if it's a problem on my end or if it's a bug introduced in the latest build, regardless I hope that this issue can be fixed easily.

**Comment by Kingcom** [comment]
This is probably due to this commit: https://github.com/Kingcom/armips/commit/8669ffd0ed0da25b2929ed3f225ade45924d46ff
The problem there was that HI16 relocations cannot be correctly done without the corresponding LO16 relocation, so they need to be matched up. In the ELF format there is a requirement that any number of HI16 entries are followed by a corresponding LO16. It's possible it works differently in this format.

Can you upload debug.obj?

**Comment by RSolidSnake11** [comment]
Here's the .obj file:
[debug.zip](https://github.com/Kingcom/armips/files/5091807/debug.zip)

**Comment by Kingcom** [comment]
Thanks. It appears that the relocations are only sorted by order of appearance, not by the same criteria as in the ELF format. I've tried to implement a suitable sorting function, can you check if everything works as expected in this branch? https://github.com/Kingcom/armips/tree/psxreloc

**Comment by RSolidSnake11** [comment]
Works great, I've also tested the game just to be sure.
Thank you so much!

**Comment by RSolidSnake11** [comment]
Actually...turns out the problem is still present, this time with a different OBJ file, here's the output:
``` Validate 0...
Validate 1...
main.asm(10) error: Mismatched R_MIPS_HI16 with R_MIPS_LO16 of a different symbol
main.asm(10) error: Mismatched R_MIPS_HI16 with R_MIPS_LO16 of a different symbol
main.asm(10) error: Mismatched R_MIPS_HI16 with R_MIPS_LO16 of a different symbol
main.asm(10) error: Mismatched R_MIPS_HI16 with R_MIPS_LO16 of a different symbol
Aborting.
``` 
Here's the object file:
[test.zip](https://github.com/Kingcom/armips/files/5092353/test.zip)

**Comment by Kingcom** [comment]
Ah, my sort order was slightly wrong. I've updated the branch. Can you try again?

**Comment by RSolidSnake11** [comment]
Tested about 3 different object files, seems to work correctly now!
Thanks again.

**Comment by Kingcom** [comment]
Great, thanks for testing. I'll see if I can come up with a regression test.
