### ISSUE TITLE
Vector loads/stores element not checked for validity

### ISSUE THREAD

**Issue by clbr** [Kingcom/armips#194]
```asm
ldv v0[1], 0(r0)
```

This successfully assembles, even though only 0 and 8 are valid element specifiers for ldv. Probably applies to all RSP vector loads and stores.

**Comment by sp1187** [comment]
Reverted by https://github.com/Kingcom/armips/commit/a40cb8ca677dde89fc149917d935cdf590a56095 as the suggestion validation was later found to be too strict for some practical uses, see the discussion in #200.
