### ISSUE TITLE
cmp with negative immediate value off by 1

### ISSUE THREAD

**Issue by sehugg** [Kingcom/armips#207]
The statement:

        cmp     r0, -32

assembles to `E370001F` (`cmn r0, 31`) but should be `E3700020` (`cmn r0, 32`) according to the [Keystone assembler](http://shell-storm.org/online/Online-Assembler-and-Disassembler/?inst=cmp+++++r0%2C+-32&arch=arm&as_format=inline#assembly).

MOV/MVN and AND/BIC seem ok though. I guess CMP/CMN work differently.

**Comment by unknownbrackets** [comment]
Oops:
https://github.com/Kingcom/armips/blob/910b23de757d72e69b54da5d0d1157f1b3abfe42/Archs/ARM/CArmInstruction.cpp#L226

The difference for MVN/NIC is those are "not" (where 31 is correct), but CMN is negative.  The above line needs to take two's complement into account.

-[Unknown]
