### ISSUE TITLE
[feature request] Either inputname() or some way to .org to end of file

### ISSUE THREAD

**Issue by garboblarg2** [Kingcom/armips#216]
I'm currently using this setup to put my code to end of file, and it works for .open with only input filename.
Switching to input+output variant unfortunately makes filesize() return zero because outputname() doesn't yet exist in the filesystem(on first "compile". on 2nd it exists and .org will unnecessarily seek further than end of file).
<pre>
;.open "base.gba","patched.gba",0x8000000 ;doesn't work as i want
.open "test.gba",0x8000000 ;works as i want
.org 0x8000000+filesize(outputname()) ;append to end of file.
</pre>

It'd be nice if there was a way to .org to end of file, either with <pre>.org filesize(inputname())</pre>
or with some sort of <pre>.org .eof</pre> that didn't involve hardcoded offsets or duplicate filename strings and I don't think that exists yet?

**Comment by Prof9** [comment]
Alternatively, you could define the input filename with an `equ`; then you don't have to duplicate the filename string.
```
INPUT_FILE equ "base.gba"
OUTPUT_FILE equ "patched.gba"

.open INPUT_FILE, OUTPUT_FILE, 0x8000000

// ...

.orga filesize(INPUT_FILE)

// ...

.close
```

**Comment by Kingcom** [comment]
Seeing how `outputname()` exists, I think it would make sense to also have an equivalent `inputname()`.

**Comment by garboblarg2** [comment]
Filename eqs is a good enough workaround, and I feel bad for posting an issue before thinking of using them..
It's slightly more clunky, but I don't have to switch opens often enough to matter.

inputname() would still be nice to have, but not as necessary as I thought.

Sorry for posting an issue and thank you for the workaround.
,,aaand I should give passing an output filename in commandline arguments another go, because that would further simplify this for me.

Again, sorry for wasting time.
