### ISSUE TITLE
Automated builds return 404 error

### ISSUE THREAD

**Issue by DavidSM64** [Kingcom/armips#223]
The page https://buildbot.orphis.net/armips/ itself is fine, but clicking any of the download links or the "see full list of builds" link returns a 404 Not Found error.

```
Not Found
The requested URL was not found on this server.

Apache/2.4.51 (Debian) Server at buildbot.orphis.net Port 443
```

**Comment by Kingcom** [comment]
Thanks for the notice! It seems like this doesn't happen if you access it through https://buildbot.orphis.net/armips/index.php. I've let Orphis know about the problem.

**Comment by DavidSM64** [comment]
Links seem to be working now. Thank you!
