### ISSUE TITLE
Feature request: $ and math operations in notice/errors/warnings

### ISSUE THREAD

**Issue by adlogic** [Kingcom/armips#31]
First of all - thank you very much for this invaluable tool, it is really a masterpiece in romhacking world I would say :)

But useful things were not implemented, which could be really useful.

1. Some way to define current address. Yes, this could be done using label, but very convenient just to put some instruction to define that. In assembers I used this was usually just a $ sign. Works this way: lhu a0,$-4 - put in a0 address of previous command. Really useful when you create some self-modifying code.

2. Some way to display an equation, based on the assembled data. Now I see only way to show plain text message, so if you for example want to know on what address is "label1" or what is the size of data between label1 and label2 - there is no easy way to display that and immediately see. Of course, it is possible to export symbol file, do manually counting, etc... - but why, if it is possible just to do all with some display command?

Hope these requests are not really complicate.

**Comment by Prof9** [comment]
The first one is already possible.

```
Additionally, "." can be used to reference the current memory
address.
```

**Comment by adlogic** [comment]
Yes, indeed, I did not noticed that in the documentation it seems, as looked in the math parser explanations. Maybe better would be to add description also there.

**Comment by Kingcom** [comment]
The second one is definitely manageable, but it would be best to wait until I finished the new expression parser (currently in a branch). It should be simple to integrate this into it when it's stable enough.

**Comment by Kingcom** [comment]
This works now in the parser branch, as can be seen in the expressions test: https://github.com/Kingcom/armips/blob/Parser/Tests/Core/Expressions/Expressions.asm
However, the new parser is still highly experimental and unstable, so it will still take quite a while until it can be merged.

**Comment by Kingcom** [comment]
It's merged now.
