### ISSUE TITLE
Recent change broke mcr and mrc for nds.

### ISSUE THREAD

**Issue by mid-kid** [Kingcom/armips#39]
A recent change changed the encoding for both the mcr and mrc instructions for the nds.
It changed, for example `mrc p15, 0, r0, c2, c0, 0`, from `10 0F 12 EE` to `10 20 B6 FF`. This "new" instruction is seen as undefined in objdump and does not run properly on the target system (3ds).

**Comment by Kingcom** [comment]
Hm, seems like it was a dumb typo. Does 23cd57f84a41e5f8b0d5cfc1e112a45473ab922f fix all of it? Your example seems to be fine now.

**Comment by mid-kid** [comment]
Yep, that fixes all. Thanks.
