### ISSUE TITLE
Feature request: big endian !

### ISSUE THREAD

**Issue by smealum** [Kingcom/armips#41]
I love armips and I use it for everything but now I'm working on a big endian arm platform and it seems armips doesn't support big endian. any chance that will change in the future ?

thanks for your great work !

**Comment by Kingcom** [comment]
Hm, it does support big endian, but it's linked to the platform so far (which are all little endian except N64). I think I'll add two generic ARM platforms, "arm-big" and "arm-little". I'll make them disregard system specific behavior like the SWI immediate being shifted to the upper halfword, too.

**Comment by Kingcom** [comment]
Didn't test it very thoroughly, but the latest commit should do the trick. Use ".arm.big" instead of ".nds".

Nice presentation, btw! I enjoyed it a lot. And great work in general, too, of course.

**Comment by smealum** [comment]
awesome ! thanks. i'll give it a try when i get time to build it.

**Comment by smealum** [comment]
finally got it built and tested it a bit, seems to work great ! i'll let you know if i run into any more issues.

thanks.
