### ISSUE TITLE
Can't compile on linux

### ISSUE THREAD

**Issue by 3ZVK** [Kingcom/armips#43]
link.txt is setup like it push the compiled file as armips in a dir where a armips dir exist, 
you could setup a build folder in root dir and link.txt output as "-o build/armips -rdynamic"

**Comment by Matsumot0** [comment]
I can compile armips on linux without any problem, but not on windows with MinGW...
http://i.imgur.com/eEFka28.png

Thanks in advance.
PS: Sorry i don't want open a issue ticket for that maybe i've miss something.

**Comment by Kingcom** [comment]
@3ZVK : I'm not really sure what you mean. Can you try to explain your issue? As @Matsumot0 said, building on Linux seems to work.

@Matsumot0 : Can you try putting this into stdafx.h, after #pragma once, and see if it helps?

```
#ifndef UNICODE
#define UNICODE
#endif

#ifndef _UNICODE
#define _UNICODE
#endif
```

**Comment by Matsumot0** [comment]
Thanks for your answer, it works almost :+1: 
I've had another invalid conversion

http://i.imgur.com/EAZCQWv.png

**Comment by Kingcom** [comment]
It looks like you don't have sufficient C++11 support (namely, for std::thread). Try looking for a newer version.

**Comment by Matsumot0** [comment]
Ok thanks i've changed something and it's almost working! but...

http://i.imgur.com/kguplS7.png

As you can see, MinGW can finalized the binary... after 100% complete :(
