### ISSUE TITLE
.open [single file] doesn't always work with .relativeinclude on

### ISSUE THREAD

**Issue by dreambottle** [Kingcom/armips#47]
```
> tools/armips.exe src/boot-patches.asm
ARMIPS Assembler v0.8.0 (Feb 20 2016 13:31:51) by Kingcom
src/boot-patches.asm(4) fatal error: Could not open file ../workdir/BOOT.BIN.patched
Aborting.
```
The contents of the asm file are:
```
.psp
.relativeinclude off
.open "../workdir/BOOT.BIN.patched", 0x08803F60
...
```
Note that neither the source, nor the target file are in current working directory.
Works fine when 2 different paths in .open are used, or when switched to .relativeinclude off

**Comment by Kingcom** [comment]
That should do it. Was accidentally using the base file name.

**Comment by dreambottle** [comment]
Thanks!
