### ISSUE TITLE
[Feature request] specify working directory from command line

### ISSUE THREAD

**Issue by dreambottle** [Kingcom/armips#48]
Currently the root path for .open commands can either be the cwd, with .relativeinclude off, or the directory of the script file, with .relativeinclude on.
This is quite limiting if asm files stay separately from binaries and then the project folder is reorganized, directories are moved etc. The paths are hardcoded to the asm file and it's not very flexible.

My idea is to allow setting the root working directory for  with a command line switch, like -root. So that we can:
`armips src/*.asm -root myfiles/`
in the build scripts, and the source remains as clean as
`.open "mycoolstuff.bin"`

**Comment by Kingcom** [comment]
Hm, sounds reasonable, and should be pretty effortless to implement. I'll work on it.

**Comment by Kingcom** [comment]
Would it make more sense to use the current or the supplied root directory for the path of the  main assembly file?

**Comment by dreambottle** [comment]
It would make sense if this option only affected the path, used when opening files with .open directive in .asm code. I also think the .relativeinclude switch should be ignored if we provide this directory from command line.
The purpose of the switch would be to control our _resources_ location from the command line, which is currently impossible.
So, in my opinion, the path of the ".asm" file should be treated as usual, or it would lead to confusion.

**Comment by Kingcom** [comment]
I wrote a simple implementation for now: https://github.com/Kingcom/armips/tree/path
Currently it just changes the working directory. Let me know if it works as expected.

**Comment by dreambottle** [comment]
Great! Works just as expected.
Thank you for adding this feature!
