### ISSUE TITLE
Tinyformat files missing when downloading as ZIP?

### ISSUE THREAD

**Issue by charleysdrpepper** [Kingcom/armips#62]
So I downloaded a ZIP from the "Clone or download" button... When I went to compile, I noticed I had build errors telling me that 'ext/tinyformat/tinyformat.h' couldn't be opened/found. So when I went to go check the directory... I went to ext, and saw the tinyformat folder, but guess what? There was nothing in it! (Neither from the directory I extracted nor the ZIP folder.)  And... if you look on this Github, you'll see that the tinyformat folder seems to be named "tinyformat @ b7f5a22" or something. (Possible glitch?)... And that folder does have its files. I did try downloading from both Firefox and Google Chrome. (Didn't think it was a browser issue.) Oh, and I use Windows 10, if that means anything. (Doubt it.)  The "Size" seems to be 191 KB (196,189 bytes).  My guess is that it is a Github glitch. - Anyone else having the problem? If not, then probably not much of a big deal since I should be able to manually copy those files myself...

**Comment by Kingcom** [comment]
This is because tinyformat is a submodule, the folder references a seperate repository. Github's download option only includes the files from the specific repository. When you clone the repository with a git client, you also need to init and update the submodules to get the files as a result.

**Comment by charleysdrpepper** [comment]
Thanks!  That sounds interesting... So I'm guessing using a Git client would be the quickest way to get everything? (For future reference.) - Would kinda help (even if just a little bit) if there was a universal download button for somewhat-new people like me. (If having an account ~3 years old still counts as "new" when you're not actively using the site much.)

**Comment by Kingcom** [comment]
It's at least the easiest and intended way, yeah. You'll need Git for Windows if you are on Windows (https://git-scm.com/download/win), on Linux you can probably install it through the package manager if it isn't already. Here's an explanation of submodules: https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by unknownbrackets** [comment]
FWIW, using [`--recursive` in git clone](http://stackoverflow.com/a/4438292) is a good approach too.

-[Unknown]
