### ISSUE TITLE
LDR-relative problems.

### ISSUE THREAD

**Issue by charleysdrpepper** [Kingcom/armips#65]
{ "ldr",	"d,[r\xF]",			0x4800,	THUMB_TYPE6,	2,	0 },
	{ "ldr",	"d,[r\xF,/#i\x08]",	0x4800,	THUMB_TYPE6,	2,	THUMB_IMMEDIATE },
	{ "ldr",	"d,[/#I\x20]",		0x4800,	THUMB_TYPE6,	2,	THUMB_IMMEDIATE|THUMB_PCR },
	{ "ldr",	"d,=/#I\x20",		0x4800,	THUMB_TYPE6,	2,	THUMB_IMMEDIATE|THUMB_POOL },

1.  2nd one - Immediate Value 
The second one ... well, I was thinking that should go from 0x0 - 0x3FC, but since the THUMB_WORD isn't a flag, >> 2, never happens. (Already tried ldr r#, [pc, 0x100] = Causes error. ; Unless maybe it was intended to be some type of word-index value instead of relative offset? (I was doubting it... especially since usually any numbers in [,] are supposed to be added together... , But hard to know if this was an actual design decision or not b/c the number must get from a 32-bit aligned address? So maybe this "issue" was accidentally posted. Haha... Or maybe not...  Since you can /still/ add code to check the alignment anyway... Hmm...))

2. 3rd one - "Stuck in infinite validation loop"
No problem with immediate value? Since THUMB_PCR does the >> 2.
Is ldr r#, [label] unusable? I get Stuck in infinite validation loop if a label is used, but not if an address number itself is used.. I probably did something wrong, though. Either case, the error is definitely not informative enough? (But I suppose it was more of a catch for unknown bugs.) v0.7d does not seem to give Stuck in infinite validation loop error? (But also seems contradictory to the newer version with the "PC relative address must be word-aligned" error..) I suppose I shall check again a bit later... Make sure I am 100% using the latest version, and see if I can figure out what's going on.

**Comment by Kingcom** [comment]
Ah, nice catch. The PC relative load is indeed an oversight. About the third one, "infinite validation loop" means that the values keep changing in such a way that addresses move back and forth. armips tries to optimize optimize opcodes and pools to take up little space, but sometimes this causes them to change size every iteration (for example, in ARM, when it sees that an immediate load can be converted to a mov instruction, but next value it loads the immediate is now smaller because it was no longer put into a pool, and now it doesn't fit into mov anymore). I'll have to check why this happens and disable the specific optimizations after too many iterations.

**Comment by Kingcom** [comment]
Can you supply a test case where the issue happens?

**Comment by charleysdrpepper** [comment]
After .gba, and between .open/.close.... it is literally:

-Stuck inside invalidation loop:
.org 0x080000C0
        ldr r0, [thelabel]
thelabel:

-PC-relative address must be word-aligned:
.org 0x080000C0
        ldr r0, [thelabel]
	mov r1, 0x20
thelabel:

-Stuck inside invalidation loop:
.org 0x080000C0
        ldr r0, [thelabel]
	mov r1, 0x20
	mov r2, 0x20
thelabel:

-Compiles okay:
.org 0x080000C0
        ldr r0, [0x080000C4]

**Comment by Kingcom** [comment]
Thanks. The latest commit should have fixed it, your test cases worked as intended for me with it (that is, error, no error, error, no error).

**Comment by charleysdrpepper** [comment]
Thanks! Seems to work now! You are welcome.

One of my experiments was to convert one of the sections in Golden Sun 2 into assembly (via a program I write) to see how that works with automated pointering...  (That game (and many others from the same company) has a number of "code files" with free space at the end of them, so it's not as hard as it would probably be for an entire game.) - Probably would do the whole game if I like my results, since I know a vast majority (not all) of the data in that game. Kind of a fun theory to how to do a game editor. (And who knows if this would challenge others to try the same with other games, if successful.)
