### ISSUE TITLE
Statement syntax proposal

### ISSUE THREAD

**Issue by sp1187** [Kingcom/armips#67]
My suggestion is that newlines are restored as statement separators, but supporting `\` at the end of a line to continue a statement into the next line, similar to how statements work in Python.
This should allow opcodes and directives to have optional first arguments, solving issue #50 and allowing MIPS `break` and `syscall` to be used without an argument. It also forbids potentially confusing syntax like `instruction1 arg instruction2 arg` in the same line.

Example:
```
addi t1, t2, \
very_long_expression_here
```

**Comment by Kingcom** [comment]
Hm, that makes sense. The other intended purpose was to allow multiple opcodes/directives on a single line. for example for longer nop chains that would otherwise blow up the number of lines quite a bit. Can you think of a decent way to handle these too?

**Comment by sp1187** [comment]
In Python you can use `;` to put multiple statements in a single line. That character is used for comments here, so you can't use that one of course, but something similar could be used.

**Comment by Kingcom** [comment]
Yeah, but when I thought about it I couldn't think of something that looked nice. The C expression syntax takes care of almost all possible symbols unfortunately.

**Comment by sp1187** [comment]
`@` is probably the most viable option, although still a bit ugly, may be sufficient for this purpose anyway. Another option may be adding a .repeat/.endrepeat directive or something similar repeating a sequence N times.

**Comment by sp1187** [comment]
The most viable character I can think of for a statement separator is backtick (`` ` ``).
A bit ugly, but some architectures in GAS seems to actually use the backtick for this purpose, and I guess it won't be used all that often anyway, so I think it would be feasible.

**Comment by sp1187** [comment]
Do you have any plans of implementing this currently? I would have tried myself but I'm afraid I don't quite understand the parser enough yet.

**Comment by Kingcom** [comment]
I think I have a decent idea how it could be implemented, but I'm afraid I don't really have the time to do the proper testing at the moment. If you want though, I could talk to you about it and the parser, like somewhere in IRC.

**Comment by sp1187** [comment]
Sounds interesting. I'm usually available at #n64dev in EFnet.
