### ISSUE TITLE
Please i Need the Latest Compiled version of Armips 0.8

### ISSUE THREAD

**Issue by PraivinRed** [Kingcom/armips#68]
Please, Anyone can upload the compiled Armips 0.8 for 32 Bit to me. i Need it but i dont have Visual Studio 2015 and its really to big to download.

Please 

Thank You

**Comment by february-sn0w** [comment]
Here is for 32bit and 64bit both binary.

http://februarysn0w.net/tool/armips.7z

**Comment by PraivinRed** [comment]
Thank You Soooooooooooooo Much
