### ISSUE TITLE
Mac OS X build of 0.8 (attached)

### ISSUE THREAD

**Issue by hippydave** [Kingcom/armips#74]
It's a pain to build on Mac, so here's a working binary, courtesy of julialy on gbatemp.

[armips.zip](https://github.com/Kingcom/armips/files/615186/armips.zip)

**Comment by queueRAM** [comment]
What were the problems you had building under OS X? What did you do to solve these problems? Were any changes to the source or additional project files needed?

**Comment by hippydave** [comment]
It doesn't build with OS X's own compiler (clang), so after seeing this guide: http://gbatemp.net/threads/compiling-luma-3ds-on-os-x.426106/
I was trying to build it with gcc 6 from Homebrew (a package manager). This failed with an error:
"suffix or operands invalid for `movq'" - which as far as I could tell from googling may have been caused by a clash between Homebrew and something else, but I couldn't get it resolved, so I obtained a binary from someone else.
So I don't think the project needed any changes, just the right set of tools to build it.

**Comment by queueRAM** [comment]
Disclaimer: I'm not the armips maintainer, so my opinion really doesn't matter. I appreciate you trying to help those who might be wanting to run armips on OS X, however, I'm personally not comfortable linking to a binary built by someone other than Kingcom.

That said, I decided to investigate building on OS X myself. I managed find someone willing to lend me time on their machine running OS X and build armips successfully on it. I installed cmake and gcc-6 through homebrew and used the following build commands:
```
$ cmake -DCMAKE_CXX_COMPILER=/usr/local/bin/g++-6 ..
$ make
$ ./armips
ARMIPS64 Assembler v0.8.0 (Nov 29 2016 19:03:51) by Kingcom
```

There may be a way to compile it with clang, but I am not as familiar with its command line options. I may investigate this more if I get access to another OS X box.

**Comment by Kingcom** [comment]
Yeah, use any such builds at your own risk... you can't know exactly who built them or how they were "customized". Ideally it should of course work on all compilers. The recent pull request may helped there. I'll close this as it's not an actual issue.
