### ISSUE TITLE
Small Idea: Adding block comments

### ISSUE THREAD

**Issue by xXGucciferXx** [Kingcom/armips#85]
I don't see my request as high priority, but some older ASM hacks have lots of block comments for documentation purposes. So, it would be useful to not only have line, but also block comments.

**Comment by Kingcom** [comment]
Ah, sorry. I somehow completely forgot this.
I think it would actually be pretty simple to do, but I'm not sure when I'd get around to it. If you want to give it a try, you'd probably just have to add the logic in this function: https://github.com/Kingcom/armips/blob/master/Parser/Tokenizer.cpp#L211
C-style block comments (/* .... */) should work, though remember that unlike the current comments, they don't necessarily extend to the end of the line

**Comment by xXGucciferXx** [comment]
Ok, I followed your advice and added it myself. I would like to add the code to your rep. Unfortunately, I am new to GitHub, so I have no idea how to do this. The code though is here:
```
void FileTokenizer::skipBlockComments()
{
	while (isBlockComment(currentLine, linePos))
	{
		lineNumber++;
		currentLine = input->readLine();
		while (!isBlockCommentEnd(currentLine,linePos))
		{
			linePos = currentLine.size();
			lineNumber++;
			currentLine = input->readLine();
		}
	}

	while (isBlockCommentEnd(currentLine, linePos))
		linePos = currentLine.size();
}
```

and added the function to FileTokenizer::init right after skipWhitespace();
