### ISSUE TITLE
.open "file.bin","file.bin",0 does not set error code

### ISSUE THREAD

**Issue by Prof9** [Kingcom/armips#99]
```
.open "file.bin","file.bin",0
```
Throws a fatal error `fatal error: Could not copy file file.bin`, but exits with error code 0.

Should exit with error code 1 (or higher) instead.

**Comment by Kingcom** [comment]
Can you check if this still happens, and if so provide a full test case? As far as I can tell, all errors lead to a return value of 1 from main.

**Comment by Prof9** [comment]
Yeah, it still happens. Using current nightly:

**test1.asm**
```ASM
.error "deliberate error"
```
**test2.asm**
```ASM
.gba
.open "test.bin","test.bin",0
.close
```
**test.bat**
```Batch
@echo off
armips test1.asm
if errorlevel 1 ( echo armips exited with errors )
armips test2.asm
if errorlevel 1 ( echo armips exited with errors )
echo done
```
Produces:
```
test1.asm(1) error: deliberate error
Aborting.
armips exited with errors
test2.asm(3) fatal error: Could not copy file test.bin
done
```
There's no "armips exited with errors" being printed after the second run.

**Comment by sp1187** [comment]
I think this error may be Windows-only, as I do not get any error messages at all in the second case on Linux when a test.bin exists. Linux is likely less restrictive about opening files multiple times than Windows here. When I do not have a test.bin file, I get `fatal error: Could not open file test.bin` as expected. 

For reference, here is the script I ported to Linux from test.bat:
```sh
armips test1.asm || echo "armips exited with errors"
armips test2.asm || echo "armips exited with errors"
echo "done"
```

and the script output:
```
/home/simon/ppriv/armipstest/test1.asm(1) error: deliberate error
Aborting.
armips exited with errors
done
```

**Comment by Prof9** [comment]
Ah, I see the confusion. You're right in that the exit code is 1 if there is no test.bin. However, if test.bin *does* exist, then it returns exit code 0 instead.

**Comment by Kingcom** [comment]
The problem is that the error is only detected in the encoding stage, as CopyFileW (correctly) fails to copy a file to itself. On Linux the copying is done manually, apparently with non-blocking files. Currently errors are not supposed to happen during the encode stage. I'll add a check to ensure the source and target files are different.
